# Array, Matrices, and Data Handling (with Numpy and Pandas)

## Part 1 (Mostly Numpy)

This is one of the most important building blocks in learning python for financial applications. Part 1 will focus on the basic functions of array using only Numpy, and part 2 introduces more commands and functions related to handling array and matrices. Toward the end of Part 2, Pandas library will be introduced. Then, part 3 uses the Pandas library more actively as well as the Numpy.

- NumPy provides the core data type for numerical analysis – arrays.
- Arrays are similar to lists or tuples.
- NumPy arrays are widely used through the Python econsystem
- In particular, the key key libraries such as pandas and statsmodel are interactively used.
- For this lecture, we mostly use an array where all elements have the same numeric type. Plus, in case of arrays, unlike lists, all dimensions have the same number of elements.


##How to use Numpy?

Use import command: import numpy. Then, use numpy.specific_command
Certain library names are long, and you can use a short-hand notation
import numpy as np

Alternatively, if you want to use only one specific command, you can use from XX import YY command

Arrays are initialized from lists (or tuples) using array. Two-dimensional arrays are initialized using lists of lists (or tuples of tuples, or lists of tuples, etc.), and higher dimensional arrays can be initialized by further nesting lists or tuples.

In [ ]:
from numpy import array

In [ ]:
#Alternatively,
#import numpy as np    Then, ... np.array
#import pandas as pd

In [ ]:
x = [0.0, 1, 2, 3, 4]

In [ ]:
type(x)

list

In [ ]:
# Convert it to an array
y = array(x)

In [ ]:
type(y)

numpy.ndarray

Two (or higher) -dimensional arrays are initialized using nested lists.

In [ ]:
y1=array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [ ]:
y1

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [ ]:
from numpy import shape

In [ ]:
shape(y)

(5,)

In [ ]:
y1.dtype

dtype('float64')

In [ ]:
y.dtype

dtype('float64')

In [ ]:
x = [0,1,2,3,4]

In [ ]:
y=array(x)
y.dtype

dtype('int64')

In [ ]:
y=array(x, dtype=float)

In [ ]:
y.dtype

dtype('float64')

In [ ]:
y

array([0., 1., 2., 3., 4.])

In [ ]:
# Make a column array
yc = array([[1.0], [2.0], [3.0], [4.0], [5.0]])

In [ ]:
yc

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

Two-dimensional arrays are rows of columns

In [ ]:
x = array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
y = array([[[1,2],[3,4]],[[5,6],[7,8]]])
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

We often need to concatenate data.

For instance,
$  x = \begin{bmatrix}
    1       & 3 \\
    2       & 4
\end{bmatrix}$ and $  y = \begin{bmatrix}
    5       & 7 \\
    9       & 10
\end{bmatrix}$ and $ z = \begin{bmatrix}
    x       \\
    y
\end{bmatrix}$

In [ ]:
x = array([[1.0,3.0],[2.0,4.0]])
y = array([[5.0,7.0],[9.0,10.0]])

In [ ]:
import numpy as np

z = np.concatenate((x,y),axis=0) #axis=0 means arrays are concatednated vertically.
z

array([[ 1.,  3.],
       [ 2.,  4.],
       [ 5.,  7.],
       [ 9., 10.]])

In [ ]:
z1 = np.concatenate((x,y),axis=1) # Horizontal Concatenation

z1

array([[ 1.,  3.,  5.,  7.],
       [ 2.,  4.,  9., 10.]])

In [ ]:
# You can use vstack (identical to axis=0) or hstack (axis=1)

In [ ]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

How to access ingredients (elements) of array

In [ ]:
x = array([1.0,2.0,3.0,4.0,5.0])

In [ ]:
x[0]

1.0

In [ ]:
x = array([[1.0,2,3],[4,5,6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
x[0,2] #second row, third column because python begins with 0

3.0

In [ ]:
type(x[1,2])

numpy.float64

In [ ]:
#Basic slicing of 1-dimensional arrays is identical to slicing a simple list, and the returned type of all slicing operations matches the array being sliced.


In [ ]:
x = array([1.0,2.0,3.0,4.0,5.0])
Y = x[:]

In [ ]:
Y

array([1., 2., 3., 4., 5.])

In [ ]:
y = x[:2]

In [ ]:
y=x[1:2]

In [ ]:
y

array([2.])

In [ ]:
y = array([[0.0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

In [ ]:
y

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [ ]:
y[:1,:] # Row 0, all columns

array([[0., 1., 2., 3., 4.]])

In [ ]:
y[:1] # Same as y[:1,:]

array([[0., 1., 2., 3., 4.]])

In [ ]:
y[:,:1] # all rows, column 0

array([[0.],
       [5.]])

In [ ]:
y[:1,0:3] # Row 0, columns 0 to 2

array([[0., 1., 2.]])

In [ ]:
y[:1][:,0:3] # Same as previous

array([[0., 1., 2.]])

In [ ]:
y[:,3:] # All rows, columns 3 and 4

array([[3., 4.],
       [8., 9.]])

In [ ]:
y = array([[[1.0,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
y[:1,:,:] # Panel 0 of 3D y

array([[[1., 2.],
        [3., 4.]]])

In [ ]:
x=[[0.0]*3]*3

In [ ]:
y = array(x)

In [ ]:
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
y = np.reshape(np.arange(25.0),(5,5))

In [ ]:
y

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [ ]:
y.flat[:]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [ ]:
# Another useful trick with array is to use tile when you want to create a block matrix


x = array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
z = np.tile(x,(2,3))
z

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

# Basic Operations Using Array

## (Matrix) Algebra

### Standard Operators

- $ + $: Addition
- $ - $: Subtraction
- $ * $: Multiplication
- $ / $: Division (Left divide)
- $ // $: Integer division
- $**$: Exponentiation, $x**y$, doing $x^y$
- $@$: Matrix Multiplication

When $x$ and $y$ are scalars, these operators work in usual ways. For arrays, it is tricky because Numpy uses certain rules that are not necessarily compatible with conventional matrix algebra. We will investigate more in the below.

In [ ]:
# Can you add, subtract, or multiply an array with a scalar? This is not a matrix algebra, but numpy does the following.
z2 = 3
z+z2

array([[4, 5, 4, 5, 4, 5],
       [6, 7, 6, 7, 6, 7],
       [4, 5, 4, 5, 4, 5],
       [6, 7, 6, 7, 6, 7]])

In [ ]:
z-z2

array([[-2, -1, -2, -1, -2, -1],
       [ 0,  1,  0,  1,  0,  1],
       [-2, -1, -2, -1, -2, -1],
       [ 0,  1,  0,  1,  0,  1]])

In [ ]:
z2-z

array([[ 2,  1,  2,  1,  2,  1],
       [ 0, -1,  0, -1,  0, -1],
       [ 2,  1,  2,  1,  2,  1],
       [ 0, -1,  0, -1,  0, -1]])

In [ ]:
z*z2

array([[ 3,  6,  3,  6,  3,  6],
       [ 9, 12,  9, 12,  9, 12],
       [ 3,  6,  3,  6,  3,  6],
       [ 9, 12,  9, 12,  9, 12]])

In [ ]:
# Again it is not the actual matrix algebra but below are the numpy operations with an array with another array with lesser dimension
z3 = [1,2,3,4,5,6]
z3

[1, 2, 3, 4, 5, 6]

In [ ]:
z+z3

array([[ 2,  4,  4,  6,  6,  8],
       [ 4,  6,  6,  8,  8, 10],
       [ 2,  4,  4,  6,  6,  8],
       [ 4,  6,  6,  8,  8, 10]])

In [ ]:
z*z3

array([[ 1,  4,  3,  8,  5, 12],
       [ 3,  8,  9, 16, 15, 24],
       [ 1,  4,  3,  8,  5, 12],
       [ 3,  8,  9, 16, 15, 24]])

# Exercises

Input the following matrices into Python as arrays

$  x = \begin{bmatrix}
    1 & 2 & 3 & 5\\
\end{bmatrix} $

$  y = \begin{bmatrix}
    1 & 2 & 1 & 2 \\ 3 & 5 & 6 & 4 \\ 5 & 9 & 1.5 & 10 \\
\end{bmatrix} $

$  Z = \begin{bmatrix}
    x & x \\ y & y \\
\end{bmatrix} $

Q1) Concatenate x to y above the first row of y and name it as K

Q2) Select x from Z

Q3) Select [x' y'] from Z, where x' and y' are transposed x and y, respectively.



## Formal matrix multiplication

In [ ]:
x = array([[1.0, 2],[ 3, 2], [3, 4]])
x

array([[1., 2.],
       [3., 2.],
       [3., 4.]])

In [ ]:
y = array([[9.0, 8],[7, 6]])
y

array([[9., 8.],
       [7., 6.]])

$x$ is a $3 × 2$ matrix, and $y$ is a $2 \times 2$ matrix. Thus, $x \times y$ will be $3 \times 2$ matrix.

In [ ]:
x@y
#1*9+2*7=23, 1*8+2*6=20 : This is the first row of the result

array([[23., 20.],
       [41., 36.],
       [55., 48.]])

## Division and Exponentiation is done in an element-by-element fashion.

In [ ]:
z= array([[1.0, 4],[ 3, 5], [3, 1]])

In [ ]:
z/x

array([[1.  , 2.  ],
       [1.  , 2.5 ],
       [1.  , 0.25]])

## Transpose? .T or .transpose() or np.transpose(x)

In [ ]:
xtr = x.transpose()
xtr

array([[1., 3., 3.],
       [2., 2., 4.]])

In [ ]:
x.T

array([[1., 3., 3.],
       [2., 2., 4.]])

In [ ]:
np.transpose(x)

array([[1., 3., 3.],
       [2., 2., 4.]])