# Array, Matrices, and Data Handling (with Numpy and Pandas)

## Part 2 (More Numpy + Introducing Pandas)

In this part, we learn some commands and functions useful for your programming. There are too many functions to cover in this lecture, so we will learn a core set of functions. Then, we add one more library to Python, Pandas, which is useful for data analytics.

## Contents

- Functions and Methods/Properties
- Convenient functions
- Special Arrays
- NaN and Inf
- Sorting and Extreme Values

In [ ]:
import numpy as np

In [ ]:
#linspace(a,b,n) produces a set of n points with an equal distance between a and b.

x=np.linspace(0,10,21)

In [ ]:
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
#logspace(a,b,n) is similar to linspace(a,b,n), except taht it makes an array of points between 10**a and 10**b

logx = np.logspace(0,1,11)

NameError: ignored

In [ ]:
logx

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])

## arange(a,b,s)

arange(a,b,n) creates an array of numbers between a and b (b not included) with a distance $s$. So, the main difference between linspace and arange lies in the way the set of points is spaced by. If only one input is provided for the arange, say arange(b), this refers to arange(0,b,1).

In [ ]:
x = np.arange(11.5)

In [ ]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x = np.arange(12)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x=np.arange(1,10,.3)
x

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

# You can create a mesh grid

In [ ]:
x = np.arange(5)
y = np.arange(3)

In [ ]:
X,Y = np.meshgrid(x,y)

In [ ]:
X

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
Y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [ ]:
np.r_[0:10:.5] # arange equivalent

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.r_[0:10:0.3]

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6, 9.9])

In [ ]:
# Additional related commands to check
# c_, ix_, mgrid_, ogrid_,...

In [ ]:
# Can we generate random (normal distribution) array?

x = np.random.randn(2,10)
x

array([[-0.45962571, -1.25578534, -0.06266895, -0.36031787, -1.51809098,
        -1.93827317,  0.71588438,  0.38529488,  1.02682798,  0.27648031],
       [-0.17731286,  0.51117623,  0.50814367,  0.26217402,  0.41249797,
        -0.90417702,  0.67136863, -0.80109326, -0.21695582,  1.44959955]])

## You can create random samples from various other distributions:
https://numpy.org/doc/1.16/reference/routines.random.html

In [ ]:
#random permutation of x drawn above
np.random.permutation(x)

array([[-1.6383711 , -0.20833419, -1.71678759,  0.54000776, -1.473469  ,
        -1.09070123, -0.5430217 , -0.85895011, -0.58735258, -0.19968494]])

In [ ]:
np.sum(x)

-7.776664691964929

In [ ]:
x.sum()

-7.776664691964929

In [ ]:
np.sum(x,1)

array([-3.19027446,  1.71542112])

In [ ]:
x.sum(1)

array([-7.77666469])

In [ ]:
np.sum(x,0)

array([-0.63693857, -0.74460911,  0.44547472, -0.09814384, -1.105593  ,
       -2.84245018,  1.38725301, -0.41579837,  0.80987215,  1.72607986])

In [ ]:
np.cumsum(x,0)

array([[-0.45962571, -1.25578534, -0.06266895, -0.36031787, -1.51809098,
        -1.93827317,  0.71588438,  0.38529488,  1.02682798,  0.27648031],
       [-0.63693857, -0.74460911,  0.44547472, -0.09814384, -1.105593  ,
        -2.84245018,  1.38725301, -0.41579837,  0.80987215,  1.72607986]])

In [ ]:
np.cumsum(x,1)

array([[-0.45962571, -1.71541106, -1.77808001, -2.13839787, -3.65648885,
        -5.59476202, -4.87887764, -4.49358275, -3.46675477, -3.19027446],
       [-0.17731286,  0.33386337,  0.84200704,  1.10418106,  1.51667904,
         0.61250202,  1.28387065,  0.4827774 ,  0.26582157,  1.71542112]])

In [ ]:
# As methods,...
x.cumsum(1)

array([[ 1.07928743,  0.37721001,  1.27543942,  1.36949988],
       [ 2.08848848,  1.27392065, -0.24009179,  0.71790588],
       [-0.54704932,  0.4954562 , -0.65380508, -1.56909567]])

In [ ]:
x.cumsum(0)

array([[ 1.07928743, -0.70207741,  0.89822941,  0.09406046],
       [ 3.1677759 , -1.51664524, -0.61578303,  1.05205813],
       [ 2.62072658, -0.47413972, -1.76504431,  0.13676754]])

In [ ]:
x

array([[ 1.07928743, -0.70207741,  0.89822941,  0.09406046],
       [ 2.08848848, -0.81456783, -1.51401244,  0.95799767],
       [-0.54704932,  1.04250552, -1.14926127, -0.91529059]])

In [ ]:
np.diff(x)

array([[-0.79615963,  1.19311639, -0.29764892, -1.15777311, -0.42018219,
         2.65415755, -0.3305895 ,  0.6415331 , -0.75034767],
       [ 0.68848909, -0.00303257, -0.24596964,  0.15032395, -1.31667499,
         1.57554565, -1.47246189,  0.58413743,  1.66655538]])

In [ ]:
np.diff(x,axis=0)

array([[ 1.00920105, -0.11249041, -2.41224185,  0.86393721],
       [-2.6355378 ,  1.85707334,  0.36475117, -1.87328826]])

In [ ]:
np.diff(x,1,axis=0)

array([[ 1.00920105, -0.11249041, -2.41224185,  0.86393721],
       [-2.6355378 ,  1.85707334,  0.36475117, -1.87328826]])

## Sorting?

In [ ]:
x = np.random.randn(5,3)

In [ ]:
x

array([[-0.61365876,  0.11918675,  0.08381229],
       [-0.07573014, -0.27730183, -0.12985448],
       [ 0.66386577,  0.7114311 ,  0.63554794],
       [ 0.72846744, -1.54696893, -2.20271902],
       [ 0.29517969, -1.42263535, -1.56002334]])

In [ ]:
np.sort(x)

array([[-0.61365876,  0.08381229,  0.11918675],
       [-0.27730183, -0.12985448, -0.07573014],
       [ 0.63554794,  0.66386577,  0.7114311 ],
       [-2.20271902, -1.54696893,  0.72846744],
       [-1.56002334, -1.42263535,  0.29517969]])

In [ ]:
np.sort(x,0)

array([[-0.61365876, -1.54696893, -2.20271902],
       [-0.07573014, -1.42263535, -1.56002334],
       [ 0.29517969, -0.27730183, -0.12985448],
       [ 0.66386577,  0.11918675,  0.08381229],
       [ 0.72846744,  0.7114311 ,  0.63554794]])

In [ ]:
np.sort(x,axis=None)

array([-2.20271902, -1.56002334, -1.54696893, -1.42263535, -0.61365876,
       -0.27730183, -0.12985448, -0.07573014,  0.08381229,  0.11918675,
        0.29517969,  0.63554794,  0.66386577,  0.7114311 ,  0.72846744])

## Nan Functions

In [ ]:
x = np.random.randn(5)
x

array([-0.81392343, -0.81975275, -1.62937969,  0.37671035, -1.75623803])

In [ ]:
x[1]= np.nan #You can add a nan number using this way.
x

array([-0.81392343,         nan, -1.62937969,  0.37671035, -1.75623803])

In [ ]:
np.sum(x)

nan

In [ ]:
np.nansum(x)

-3.82283079327737

In [ ]:
sum(x[np.logical_not(np.isnan(x))]) # A verbose, alternative way

-2.8255988456093584

In [ ]:
np.isnan(x) # What does 'isnan' do?

array([False,  True, False, False, False])

In [ ]:
np.mean(x)

nan

In [ ]:
np.nanmean(x)

-0.9557076983193425

In [ ]:
np.nancumsum(x)

array([-0.81392343, -0.81392343, -2.44330311, -2.06659276, -3.82283079])

Also check nanmax, nanargmax, nanmin, nanargmin, etc.

# There are useful functions that generate arrays we often need to build

## ones
## zeros
## empty
## eye, identity



In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty((2,2))

array([[-1.66321233, -1.409716  ],
       [ 0.79207063, -0.54474114]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Reshaping arrays
You can reshape or resize ndarray objects. Reshape function provides another view on the same data points, whereas Resize function produces a new object.


In [ ]:
X = np.arange(16)

In [ ]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
X[1] =20 # Remeber, you can modify some elements in array.
X

array([ 0, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
X.shape

(16,)

In [ ]:
X = np.reshape(X,(2,8))
X

array([[ 0, 20,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
X2 = np.resize(X,(3,3))
X2

array([[ 0, 20,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
X3 = np.resize(X,(2,5))
X3

array([[ 0, 20,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [ ]:
X4 = np.resize(X,(5,5))
X4

array([[ 0, 20,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15,  0, 20,  2,  3],
       [ 4,  5,  6,  7,  8]])

# Linear algebra functions

Note: Not all, but some functions use the following format (numpy.linalg.XXX)

## T or transpose
## diag
## triu, tril
## linalg.svd

## lstsq
## cholesky
## det
## eig
## inv
## trace
## kron
## matrix_rank

In [ ]:
X

array([[ 0, 20,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
X.T # transpose

array([[ 0,  8],
       [20,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [ ]:
#Alternatively,
X.transpose()

array([[ 0,  8],
       [20,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [ ]:
np.diag(X4) # Diagonal elements

array([ 0,  6, 12,  2,  8])

In [ ]:
np.triu(X4) #Upper triangular matrix

array([[ 0, 20,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0,  2,  3],
       [ 0,  0,  0,  0,  8]])

In [ ]:
np.tril(X) #Lower triangular matrix

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [8, 9, 0, 0, 0, 0, 0, 0]])

In [ ]:
X = X.reshape((4,4))
X

array([[ 0, 20,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
y =np.reshape(np.random.randn(128,1),(32,4))

In [ ]:
u, s, vh = np.linalg.svd(y) # singular value decomposition X=USV'

In [ ]:
np.size(u)

1024

In [ ]:
s

array([6.56860286, 6.26391178, 5.90154329, 4.16672781])

In [ ]:
vh

array([[ 0.48711622,  0.19719861,  0.78475115, -0.32862763],
       [-0.68042771,  0.2712934 ,  0.53203218,  0.42468787],
       [-0.44103396, -0.68017232,  0.21692482, -0.54387342],
       [ 0.32438399, -0.65182683,  0.23248875,  0.64486107]])

In [ ]:
x = np.array([[1,.5],[.5,1]])
x

array([[1. , 0.5],
       [0.5, 1. ]])

In [ ]:
xInv = np.linalg.inv(x) #Inverse matrix

In [ ]:
xInv

array([[ 1.33333333, -0.66666667],
       [-0.66666667,  1.33333333]])

# An Example using Numpy: Regression

Let's take a look at the following linear equation system.

\begin{align}
 b_1 + b_2 = 5 \\
 b_1 + b_2 = 3 \\
 b_1 + b_2 = 7 \\
 b_2 = 1
 \end{align}

In matrix form,

\begin{equation*}
\begin{bmatrix}
1 & 1 \\
1 & 1 \\
1 & 1 \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
b_1 \\
b_2 \\
\end{bmatrix} =
\begin{bmatrix}
5 \\
3 \\
7 \\
1
\end{bmatrix}
\end{equation*}
or
$Xb = y$

As you can see, this system has no solutions. But what if we think of $X$ as input data and $y$ as outcome data. For instance, the first column of $X$ is an indicator that shows whether a company pay makes positive profits, and the second column of $X$ indicates if the company pays dividend. Suppose that $y$ is the current stock price of the four companies.

The dimension of $X$ is $4 \times 2$. So, we can reduce the dimension by multiplying both sides by $X^T$ (transpose):

\begin{align}
X^T X b = X^T y ⟹ b = (X^T X)^{-1} X^T y
\end{align}

This is the punchline of regression, which is a form of projection to find a solution from this type of equation systems.

Let's code this in the below.

In [ ]:
X = np.array([1,1,1,1,1,1,0,1])

In [ ]:
X = np.reshape(X,(4,2)) # Alternatively, X = X.reshape([4,2])
X

array([[1, 1],
       [1, 1],
       [1, 1],
       [0, 1]])

In [ ]:
y = np.array([5,3,7,1])
y = y.reshape([4,1])
y

array([[5],
       [3],
       [7],
       [1]])

Because it is annoying to keep using np.linalg.inv if we need to keep using the inverse function, we can use 'from numpy.linalg import inv'.

In [ ]:
from numpy.linalg import inv

b = inv(X.T @ X) @ (X.T @ y)

print(b)

[[4.]
 [1.]]


# An Example with Numpy: Black-Scholes Model of European Option Pricing (Monte Carlo Simulation Method)
The underlying stock (asset) price at time $T$ is described by the following equation:

$ S_T = S_0 exp \left( (r- \frac{1}{2}\sigma^2)T + \sigma \sqrt{T} z \right)$, where $z$ is the standard Brownian motion under a risk-neutral ($Q$) measure, and $r$ is the constant risk-free rate.

Then, a derivate asset such as an European call option value today (time $0$) with strike price $K$ and an expiry ($T$) under the no-arbitrage condition is

\begin{equation}
C_0 = e^{-rT} E_0^Q \left( max(S_{T}-K,0)\right)
\end{equation}

There are several ways to solve the above problem but a simulation-based method uses the ideas that i) the expectation value is analogous to the sample average (analogy principle), and ii) the computer can simulate many sample paths to comput such averages. That is, we simulate $S$ up to time $T$ for $I$ times then compute the average with the option payoff:

\begin{equation}
C_0 \approx e^{-rT} \frac{1}{I} \sum_{i=1}^{I}( max(S_{T}(i)-K,0))
\end{equation}



In [ ]:
from math import sqrt, log

# Parameters
S0 = 100.0;
K = 101.0;
T = 1.0;
r = 0.02;
sigma = 0.15;

I=5*10**5;

z= np.random.standard_normal(I)

ST = S0*np.exp((r-0.5*sigma ** 2)*T+sigma*sqrt(T)*z)

hT = np.maximum(ST-K,0)

C0= np.exp(-r*T)*np.mean(hT)

print('Value of the European Call option %5.3f.' % C0)



Value of the European Call option 6.449.


Compare with the actual formula

In [ ]:
from scipy.stats import norm

# S is stock price
# K is strike price
# T is maturity
# r is continuously compounded rate
# sigma is the volatility of stock price
def call(S, K, T, r, sigma):
    cdf = norm.cdf
    d1 = (log(S/K) + (r + sigma**2 / 2.)*T) / (sigma * sqrt(T))
    d2 = d1 - sigma * sqrt(T)
    return S * cdf(d1) - K * np.exp(- r * T) * cdf(d2)

def main():
    print(call(100, 101, 1.0, 0.02, 0.15))

In [ ]:
main()

6.461925840199832


Question: Can we use the same method to price Americal-style derivatives in which exercise timing is also to be chosen?



\begin{equation}
V_0 = sup_{\tau \in \{0,\Delta t, 2 \Delta t,...,T \}} e^{-rT} E_0^Q \left( F_{\tau}(S_{\tau})\right)
\end{equation}

 After all, we can think recursively of the structure of this problem by solving backwards.

At each given point of time $t$ and the price of the underlying asset $s$,

\begin{equation}
V_t(s) = max (F_t(s),C_t(s)),
\end{equation}
where $C_t(s) = E_t^Q(e^{-r \Delta t} V_{t+\Delta t}(S_{t+\Delta t})|S_t=s)$ is the continuation value of the option given $S_t = s$

Let's try solving for this after we learn function and loops.



Question: Can we extend the above model to include a stochastic and time-varying volatility? e.g., Heston model or k-regime volatility model

Yes. We can try an intuitive one. For instance, there are two possible volatility values $\sigma_{low}$ and $\sigma_{high}$ with the latter being higher than the former. In most cases, stock volatility is low, but from time to time, volatility is high and persistent for a while.



# Pandas

## Data Structures

- Series, DataFrames, and Panels
- A Series behaves similar to a NumPy array.
- We can set up a Series via a list, tuple, array, or a dictionary.
- A Series has another column, called an index, which makes important differnces.


In [ ]:
import pandas as pd

In [ ]:
a = np.array([0.1, 1.2, 2.3, 3.4, 4.5])
a

array([0.1, 1.2, 2.3, 3.4, 4.5])

In [ ]:
s=pd.Series(a)
s

0    0.1
1    1.2
2    2.3
3    3.4
4    4.5
dtype: float64

In [ ]:
s = pd.Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a','b','c','d','e'])

In [ ]:
s

a    0.1
b    1.2
c    2.3
d    3.4
e    4.5
dtype: float64

In [ ]:
s['a']

0.1

In [ ]:
s[0]

0.1

In [ ]:
s.iloc[0]

0.1

In [ ]:
s.loc['a']

0.1

In [ ]:
s[['a','d']]

a    0.1
d    3.4
dtype: float64

In [ ]:
s.iloc[:3]

a    0.1
b    1.2
c    2.3
dtype: float64

In [ ]:
s.loc[['a','d']]

a    0.1
d    3.4
dtype: float64

In [ ]:
s.iloc[[0,3]]

a    0.1
d    3.4
dtype: float64

In [ ]:
s1 = pd.Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a','b','c','a','b'])

In [ ]:
s1.loc['a']

a    0.1
a    3.4
dtype: float64

In [ ]:
s1.describe() # Create summary statistics

count    5.000000
mean     2.300000
std      1.739253
min      0.100000
25%      1.200000
50%      2.300000
75%      3.400000
max      4.500000
dtype: float64

In [ ]:
s2 = pd.Series(np.arange(1.0,4.0),index=['a','b','c'])
s2

a    1.0
b    2.0
c    3.0
dtype: float64

In [ ]:
s3 = pd.Series(np.arange(1.0,4.0),index=['c','d','e'])

In [ ]:
s4 = s2 + s3

In [ ]:
s4

a    NaN
b    NaN
c    4.0
d    NaN
e    NaN
dtype: float64

In [ ]:
s4.dropna()

c    4.0
dtype: float64

In [ ]:
# You can drop a specific element using drop()
s4.drop('a')

b    NaN
c    4.0
d    NaN
e    NaN
dtype: float64

In [ ]:
s4.drop(['d','e'])

a    NaN
b    NaN
c    4.0
dtype: float64

In [ ]:
# You can fill all null values in a series with a specific value

s4.fillna(0.0)

a    0.0
b    0.0
c    4.0
d    0.0
e    0.0
dtype: float64

In [ ]:
s4.append(pd.Series([5,4,3,2,1],index=['f','g','h','k','l']))

a    NaN
b    NaN
c    4.0
d    NaN
e    NaN
f    5.0
g    4.0
h    3.0
k    2.0
l    1.0
dtype: float64

In [ ]:
# update

s1 = pd.Series(np.arange(1.0,4.0),index=['a','b','c'])
s1

a    1.0
b    2.0
c    3.0
dtype: float64

In [ ]:
s2 = pd.Series(-1.0*np.arange(1.0,4.0),index=['c','d','e'])

In [ ]:
s1.update(s2)

In [ ]:
s1

a    1.0
b    2.0
c   -1.0
dtype: float64

You can create a series using dictionaries.

In [ ]:
s = pd.Series({'a':0.1 ,'b': 1.2, 'c': 2.3, 'd':3.4, 'e': 4.5})

In [ ]:
s*3

a     0.3
b     3.6
c     6.9
d    10.2
e    13.5
dtype: float64

In [ ]:
2*s-2

a   -1.8
b    0.4
c    2.6
d    4.8
e    7.0
dtype: float64

In [ ]:
s1 = pd.Series(np.arange(10.0,20.0))

In [ ]:
s1.describe()

count    10.00000
mean     14.50000
std       3.02765
min      10.00000
25%      12.25000
50%      14.50000
75%      16.75000
max      19.00000
dtype: float64

In [ ]:
sumstat = s1.describe()

In [ ]:
sumstat['max']

19.0

In [ ]:
for it in range(0,10):
  print(it)
  it += 1

0
1
2
3
4
5
6
7
8
9
